// Minimal Phase-1 app shell. It runs WITHOUT any database — the drift
// data layer arrives in Phase 2 (see docs/roadmap.md).
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'l10n/app_localizations.dart';
import 'ui/einstellungen.dart';
import 'ui/statistik.dart';
import 'ui/tagebuch.dart';
import 'ui/zyklus.dart';

void main() {
  runApp(const ProviderScope(child: CycleApp()));
}

/// Root widget: Material app, German-first localization.
/// Localization is generated by `flutter gen-l10n` (see l10n.yaml); the code
/// lives in lib/l10n and is imported as a real package file below.
class CycleApp extends StatelessWidget {
  const CycleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // TODO(phase-2): replace this hard-coded default locale with a
      // Riverpod-backed locale provider powering the de/en language switcher
      // in the settings screen (deferred to Phase 2, see docs/roadmap.md).
      // Until then German is the displayed language.
      locale: const Locale('de'),
      onGenerateTitle: (context) => AppLocalizations.of(context).appTitle,
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('de'), // German first — base language of the app.
        Locale('en'),
      ],
      home: const _HomeShell(),
    );
  }
}

class _HomeShell extends StatefulWidget {
  const _HomeShell();

  @override
  State<_HomeShell> createState() => _HomeShellState();
}

class _HomeShellState extends State<_HomeShell> {
  int _index = 0;

  static const List<Widget> _screens = [
    TagebuchScreen(),
    ZyklusScreen(),
    StatistikScreen(),
    EinstellungenScreen(),
  ];

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context);
    return Scaffold(
      body: _screens[_index],
      bottomNavigationBar: NavigationBar(
        selectedIndex: _index,
        onDestinationSelected: (int newIndex) => setState(() => _index = newIndex),
        destinations: [
          NavigationDestination(
            icon: const Icon(Icons.event_outlined),
            selectedIcon: const Icon(Icons.event),
            label: l10n.navTagebuch,
          ),
          NavigationDestination(
            icon: const Icon(Icons.loop_outlined),
            selectedIcon: const Icon(Icons.loop),
            label: l10n.navZyklus,
          ),
          NavigationDestination(
            icon: const Icon(Icons.bar_chart_outlined),
            selectedIcon: const Icon(Icons.bar_chart),
            label: l10n.navStatistik,
          ),
          NavigationDestination(
            icon: const Icon(Icons.settings_outlined),
            selectedIcon: const Icon(Icons.settings),
            label: l10n.navEinstellungen,
          ),
        ],
      ),
    );
  }
}
