// Tests of the PDF generation layer (lib/pdf/cycle_pdf.dart): the pure
// header-facts function (with the anonymize mapping), the rail-caption
// legends (the pure strings the private scaffold rows use) and the
// byte-stream smoke checks of the generated document.
//
// Structural page-count checks rely on the layout planner (the one-cycle-
// per-page rule); the generated byte stream itself is only smoke-checked
// (non-empty, PDF signature, the uncompressed page markers) — the PDF
// structure is deliberately not parsed beyond countable markers — except
// where a rendering fact (e.g. the weekend band shade) is pinned verbatim
// in the uncompressed content stream.
import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

import 'package:cycle_app/domain/band_layout.dart';
import 'package:cycle_app/domain/cervix.dart';
import 'package:cycle_app/domain/cycle_grouping.dart';
import 'package:cycle_app/domain/date_only.dart';
import 'package:cycle_app/domain/marks.dart';
import 'package:cycle_app/domain/models.dart';
import 'package:cycle_app/domain/mucus.dart';
import 'package:cycle_app/domain/pdf_export_model.dart';
import 'package:cycle_app/domain/temperature_range.dart';
import 'package:cycle_app/pdf/cycle_pdf.dart';
import 'package:cycle_app/pdf/pdf_axis.dart';
import 'package:cycle_app/pdf/pdf_layout.dart';
import 'package:cycle_app/pdf/pdf_symbols.dart';
import 'package:flutter_test/flutter_test.dart';

DateTime d(int month, int day) => DateTime.utc(2026, month, day);

const _fakeModel = PdfExportModel(
  cycles: [],
  markOpenedIndexes: [0],
  overlays: [],
  observedCyclesOutsideApp: 3,
  name: 'Maria Muster',
  birthDate: null,
  shortestCycleLengths: [27],
  earliestFirstHigherCycleDays: [14],
);

/// Fixture data: two mark-opened cycles (Mar 1..28: 28 days; Mar 29..Apr 28:
/// 31 days), notes on some days with umlauts and non-Latin-1 glyphs.
List<DailyEntry> fixtureEntries() => [
  for (var i = 0; i < 28; i++)
    DailyEntry(
      date: d(3, 1 + i),
      bbtC: 36.0 + (i % 10) / 10,
      notes: i == 3
          ? 'Querdenken im Büro — schöner Tag ß'
          : (i == 10 ? 'Ж α ž' : null),
    ),
  for (var i = 0; i < 31; i++) DailyEntry(date: d(3, 29 + i), bbtC: 36.2),
];

List<CycleMark> fixtureMarks() => [
  CycleMark(date: d(3, 1), type: CycleMarkTypes.cycleStart),
  CycleMark(date: d(3, 29), type: CycleMarkTypes.cycleStart),
];

PdfExportModel fixtureModel() => buildPdfExportModel(
  entries: fixtureEntries(),
  marks: fixtureMarks(),
  observedCyclesOutsideApp: 3,
  name: 'Maria Muster',
  birthDate: d(12, 24),
  // The span extension runs the LAST cycle out to "today"; the fixture
  // pins the clock at the second cycle's last tracked day so the 2-cycle
  // plan below stays deterministic.
  today: d(4, 28),
);

/// The bundled asset font, read from the checkout (the smoke path mirrors
/// what the app loads via rootBundle; see lib/pdf/cycle_pdf.dart).
List<int> fixtureFontBytes() =>
    File('assets/fonts/NotoSans-Regular.ttf').readAsBytesSync();

/// Counts the uncompressed page markers: with `compress: false` every page
/// object dictionary appears verbatim as `/Type/Page/` (the `/Pages` node
/// does not match — its "Page" is followed by an "s", not a "/").
int countPageMarkers(List<int> bytes) {
  final pattern = '/Type/Page/'.codeUnits;
  var count = 0;
  for (var i = 0; i + pattern.length <= bytes.length; i++) {
    var hit = true;
    for (var j = 0; j < pattern.length; j++) {
      if (bytes[i + j] != pattern[j]) {
        hit = false;
        break;
      }
    }
    if (hit) count++;
  }
  return count;
}

String valueOf(List<({String label, String value})> facts, String label) =>
    facts.firstWhere((f) => f.label == label).value;

/// All fill-color operations (`r g b rg`) of one page content stream, as
/// channel tuples in emission order. Uncompressed generation emits the
/// colors verbatim; the pdf package's number formatting is absorbed by
/// the comparison tolerance below.
List<List<double>> fillColorTuples(String stream) => [
  for (final match in RegExp(
    r'([0-9.]+) ([0-9.]+) ([0-9.]+) rg',
  ).allMatches(stream))
    [
      double.parse(match.group(1)!),
      double.parse(match.group(2)!),
      double.parse(match.group(3)!),
    ],
];

/// The print-friendly weekend shade: near-white Light GRAY (all three
/// channels equal, luminance ~230) — never a pale color, and far from
/// every ink/accent darkness so nothing above it loses legibility.
const _weekendShade = 230 / 255;

/// The generated fixture document, uncompressed so the content streams
/// stay verbatim (byte-level checks).
Future<List<int>> generateFixture() => generatePdfBytes(
  model: fixtureModel(),
  fontBytes: fixtureFontBytes(),
  options: PdfExportOptions(anonymized: false),
  compress: false,
);

/// The [index]-th page's content stream bytes (0-based, print order): the
/// index-th `/Contents <n> 0 R` de-referenced, uncompressed stream
/// (compress: false).
String pageContentStream(List<int> bytes, int index) {
  final latin = latin1.decode(bytes);
  final refs = RegExp(r'/Contents (\d+) 0 R').allMatches(latin).toList();
  if (index >= refs.length) {
    fail('page $index has no /Contents reference (found ${refs.length})');
  }
  final n = refs[index].group(1)!;
  final obj = RegExp('$n 0 obj(.*?)endstream', dotAll: true).firstMatch(latin);
  if (obj == null) {
    fail('content object $n not found');
  }
  final start = obj.group(1)!.indexOf('stream\n');
  return obj.group(1)!.substring(start + 'stream\n'.length);
}

/// The first page's content stream bytes.
String firstPageContentStream(List<int> bytes) => pageContentStream(bytes, 0);

// Content-stream extraction: the document is generated UNCOMPRESSED
// (compress: false), so these operator reads are byte-exact.

/// One extracted text run: the decoded text, its baseline origin and the used
/// font size, in page coordinates (y-up).
final class PdfTextRun {
  const PdfTextRun(this.text, this.x, this.y, this.fontSize);

  final String text;
  final double x;
  final double y;
  final double fontSize;
}

/// One painted path of the page: its color (fill or stroke), whether it
/// is filled, and the bounding box of the path's points, in page
/// coordinates (y-up).
final class PdfInkPath {
  const PdfInkPath(
    this.color,
    this.minX,
    this.minY,
    this.maxX,
    this.maxY, {
    this.filled = true,
  });

  final List<double> color;
  final double minX;
  final double minY;
  final double maxX;
  final double maxY;

  final bool filled;
}

/// The document's ToUnicode CMap: glyph code → Unicode rune (the pdf package
/// writes one CMap per font as `beginbfchar <code> <unicode> endbfchar`).
Map<int, int> _codeToRuneMap(String document) {
  final map = <int, int>{};
  final block = RegExp('beginbfchar([\\s\\S]*?)endbfchar');
  final entry = RegExp('<([0-9A-F]{4})> <([0-9A-F]{4})>');
  for (final match in block.allMatches(document)) {
    for (final pair in entry.allMatches(match.group(1)!)) {
      map[int.parse(pair.group(1)!, radix: 16)] = int.parse(
        pair.group(2)!,
        radix: 16,
      );
    }
  }
  return map;
}

/// A 2D transform as the PDF operand order (a b c d e f); the returned matrix
/// applies [inner] first, then [outer].
List<double> _compose(List<double> outer, List<double> inner) => [
  outer[0] * inner[0] + outer[2] * inner[1],
  outer[1] * inner[0] + outer[3] * inner[1],
  outer[0] * inner[2] + outer[2] * inner[3],
  outer[1] * inner[2] + outer[3] * inner[3],
  outer[0] * inner[4] + outer[2] * inner[5] + outer[4],
  outer[1] * inner[4] + outer[3] * inner[5] + outer[5],
];

List<double> _apply(List<double> m, double x, double y) => [
  m[0] * x + m[2] * y + m[4],
  m[1] * x + m[3] * y + m[5],
];

PdfInkPath _pathOf(
  List<double> color,
  List<List<double>> points, {
  bool filled = true,
}) {
  var minX = points.first[0];
  var minY = points.first[1];
  var maxX = minX;
  var maxY = minY;
  for (final p in points.skip(1)) {
    if (p[0] < minX) minX = p[0];
    if (p[1] < minY) minY = p[1];
    if (p[0] > maxX) maxX = p[0];
    if (p[1] > maxY) maxY = p[1];
  }
  return PdfInkPath(color, minX, minY, maxX, maxY, filled: filled);
}

/// Extracts a page's (default: the first's) text runs and painted paths
/// (fills and ink strokes).
(List<PdfTextRun>, List<PdfInkPath>) extractPageContent(
  List<int> bytes, {
  int page = 0,
}) {
  final document = latin1.decode(bytes);
  final runes = _codeToRuneMap(document);
  final tokens = RegExp(
    '[^ ]+',
  ).allMatches(pageContentStream(bytes, page)).map((m) => m.group(0)!).toList();

  final runs = <PdfTextRun>[];
  final paths = <PdfInkPath>[];

  var ctm = <double>[1, 0, 0, 1, 0, 0];
  final saved = <List<double>>[];
  final pending = <double>[];
  final pathPoints = <List<double>>[];
  var fill = <double>[0, 0, 0];
  var stroke = <double>[0, 0, 0];
  double fontSize = 0;
  double textX = 0;
  double textY = 0;

  for (final token in tokens) {
    final value = double.tryParse(token);
    if (value != null) {
      pending.add(value);
      continue;
    }
    if (token.startsWith('[') && token.endsWith(']TJ')) {
      // The text-showing token carries the font's glyph codes as one hex
      // string: "[<0123…>]TJ" (Identity-H, 2-byte codes).
      final hex = RegExp('<([0-9A-Fa-f]*)>').firstMatch(token)!.group(1)!;
      final text = StringBuffer();
      for (var i = 0; i + 4 <= hex.length; i += 4) {
        final code = int.parse(hex.substring(i, i + 4), radix: 16);
        final rune = runes[code];
        if (rune != null && rune > 0) text.writeCharCode(rune);
      }
      runs.add(PdfTextRun(text.toString(), textX, textY, fontSize));
      pending.clear();
      continue;
    }
    switch (token) {
      case 'q':
        saved.add(ctm);
      case 'Q':
        ctm = saved.removeLast();
      case 'cm':
        ctm = _compose(ctm, [
          pending[0],
          pending[1],
          pending[2],
          pending[3],
          pending[4],
          pending[5],
        ]);
      case 'm' || 'l':
        pathPoints.add(_apply(ctm, pending[pending.length - 2], pending.last));
      case 'c':
        for (var i = pending.length - 6; i < pending.length; i += 2) {
          pathPoints.add(_apply(ctm, pending[i], pending[i + 1]));
        }
      case 're':
        final x = pending[pending.length - 4];
        final y = pending[pending.length - 3];
        pathPoints
          ..add(_apply(ctm, x, y))
          ..add(
            _apply(
              ctm,
              x + pending[pending.length - 2],
              y + pending[pending.length - 1],
            ),
          );
      case 'rg':
        fill = pending.sublist(pending.length - 3);
      case 'RG':
        stroke = pending.sublist(pending.length - 3);
      case 'f' || 'f*':
        if (pathPoints.isNotEmpty) paths.add(_pathOf(fill, pathPoints));
        pathPoints.clear();
      case 'S' || 's':
        if (pathPoints.isNotEmpty) {
          paths.add(_pathOf(stroke, pathPoints, filled: false));
        }
        pathPoints.clear();
      case 'Td':
        final at = _apply(ctm, pending[pending.length - 2], pending.last);
        textX = at[0];
        textY = at[1];
      case 'Tf':
        fontSize = pending.last;
      // Any other path-closing operator discards the collected points
      // (the clips and the multiline-paint combos are not needed; fills
      // and ink strokes are extracted above).
      default:
        if (pathPoints.isNotEmpty) pathPoints.clear();
    }
    pending.clear();
  }
  return (runs, paths);
}

// ---------------------------------------------------------------------------
// The in-plot chart-marks fixture: sex (one triple-timing day, one end-only
// day), mucus signs (S with quality, f/S), a mucus-peak mark on the S day and
// a Mittelschmerz day — on a continuous window (column == calendar offset
// from the Mar 1 cycle start), one page.
// ---------------------------------------------------------------------------

List<DailyEntry> markFixtureEntries() => [
  for (var i = 0; i < 14; i++)
    DailyEntry(
      date: d(3, 1 + i),
      bbtC: 36.5,
      sexTimings: i == 2
          ? (SexTiming.start.bit | SexTiming.middle.bit | SexTiming.end.bit)
          : (i == 3 ? SexTiming.end.bit : 0),
      mucusSign: i == 5 ? MucusSign.s : (i == 6 ? MucusSign.fs : null),
      mucusQuality: i == 5 ? MucusQuality.ew : null,
      painMittelschmerz: i == 8,
    ),
];

List<CycleMark> markFixtureMarks() => [
  CycleMark(date: d(3, 1), type: CycleMarkTypes.cycleStart),
  CycleMark(date: d(3, 6), type: CycleMarkTypes.mucusPeakDay),
];

PdfExportModel markFixtureModel({TemperatureRange? range}) =>
    buildPdfExportModel(
      entries: markFixtureEntries(),
      marks: markFixtureMarks(),
      temperatureRange: range ?? TemperatureRange.defaults,
      today: d(3, 14),
    );

Future<List<int>> generateMarkFixture({TemperatureRange? range}) =>
    generatePdfBytes(
      model: markFixtureModel(range: range),
      fontBytes: fixtureFontBytes(),
      options: PdfExportOptions(anonymized: false),
      compress: false,
    );

// ---------------------------------------------------------------------------
// The merged notes-band fixture: day 0 records the full stack (closed
// opening in the low slot + soft firmness + breast pain + note), day 1 an
// unreachable open cervix with the half-soft firmness alone, day 2 breast
// pain + note without any cervix observation and day 3 a middle opening
// in the middle slot alone — on a continuous window (column == calendar
// offset from the Mar 1 cycle start), one page.
// ---------------------------------------------------------------------------

List<DailyEntry> bandFixtureEntries() => [
  DailyEntry(
    date: d(3, 1),
    bbtC: 36.5,
    cervixPosition: CervixPosition.low,
    cervixOpening: CervixOpening.closed,
    cervixFirmness: CervixFirmness.soft,
    painBreast: true,
    notes: 'Erste Notiz',
  ),
  DailyEntry(
    date: d(3, 2),
    bbtC: 36.5,
    cervixPosition: CervixPosition.unreachable,
    cervixOpening: CervixOpening.open,
    cervixFirmness: CervixFirmness.halfSoft,
  ),
  DailyEntry(
    date: d(3, 3),
    bbtC: 36.5,
    painBreast: true,
    notes: 'Zweite Notiz',
  ),
  DailyEntry(
    date: d(3, 4),
    bbtC: 36.5,
    cervixPosition: CervixPosition.medium,
    cervixOpening: CervixOpening.middle,
  ),
  for (var i = 4; i < 14; i++) DailyEntry(date: d(3, 1 + i), bbtC: 36.5),
];

List<CycleMark> bandFixtureMarks() => [
  CycleMark(date: d(3, 1), type: CycleMarkTypes.cycleStart),
];

PdfExportModel bandFixtureModel() => buildPdfExportModel(
  entries: bandFixtureEntries(),
  marks: bandFixtureMarks(),
  today: d(3, 14),
);

Future<List<int>> generateBandFixture() => generatePdfBytes(
  model: bandFixtureModel(),
  fontBytes: fixtureFontBytes(),
  options: PdfExportOptions(anonymized: false),
  compress: false,
);

// The in-plot day-numbers fixture: six low measurements at 36.2, then the
// first higher on day 7 (marked) — the evaluation numbers the lows 6…1, and
// a mucus S on one low day anchors the rows' relative geometry. One page.
List<DailyEntry> numberFixtureEntries() => [
  for (var i = 0; i <= 7; i++)
    DailyEntry(
      date: d(3, 1 + i),
      bbtC: i <= 5 ? 36.2 : 36.8,
      mucusSign: i == 3 ? MucusSign.s : null,
    ),
];

List<CycleMark> numberFixtureMarks() => [
  CycleMark(date: d(3, 1), type: CycleMarkTypes.cycleStart),
  CycleMark(date: d(3, 7), type: CycleMarkTypes.firstHigherMeasurement),
];

PdfExportModel numberFixtureModel({TemperatureRange? range}) =>
    buildPdfExportModel(
      entries: numberFixtureEntries(),
      marks: numberFixtureMarks(),
      temperatureRange: range ?? TemperatureRange.defaults,
      today: d(3, 8),
    );

Future<List<int>> generateNumberFixture({TemperatureRange? range}) =>
    generatePdfBytes(
      model: numberFixtureModel(range: range),
      fontBytes: fixtureFontBytes(),
      options: PdfExportOptions(anonymized: false),
      compress: false,
    );

void main() {
  group('rail captions (the paper-form row legends)', () {
    test('the below-plot temperature value row\'s rail legend reads exactly '
        '"Temperatur in °C" (consistent with Zyklustag/Datum styling)', () {
      expect(pdfRailCaptionTemperatureValues, 'Temperatur in °C');
    });

    test('the day-number and date rows keep their legends', () {
      expect(pdfRailCaptionDayNumbers, 'Zyklustag');
      expect(pdfRailCaptionDates, 'Datum');
    });

    test('the legends are pairwise distinct labels', () {
      final captions = [
        pdfRailCaptionDayNumbers,
        pdfRailCaptionDates,
        pdfRailCaptionTemperatureValues,
      ];
      expect(captions.toSet(), hasLength(captions.length));
    });
  });

  group('header facts (pure)', () {
    test('a named export shows the identifying values and the numbers', () {
      final facts = pdfHeaderFacts(
        model: _fakeModel,
        anonymized: false,
        cycleIndex: 0,
      );

      expect(valueOf(facts, 'Name'), 'Maria Muster');
      // No birth date stored: the "—" convention.
      expect(valueOf(facts, 'Geburtsdatum'), '—');
      // The count is the page's ordinal (the "Zyklus" line's exact source
      // figure): outside-app 3 + this cycle's 0-based index 0 + 1.
      expect(valueOf(facts, 'Beobachtete Zyklen'), '4');
      expect(valueOf(facts, 'Kürzester Zyklus'), '27 Tage');
      expect(valueOf(facts, 'Früheste erste höhere Messung'), 'Zyklustag 14');
    });

    test('a stored birth date is formatted as the German calendar date', () {
      final model = PdfExportModel(
        cycles: const [],
        markOpenedIndexes: const [0],
        overlays: const [],
        observedCyclesOutsideApp: 0,
        name: null,
        birthDate: DateTime.utc(1980, 12, 24),
        shortestCycleLengths: [null],
        earliestFirstHigherCycleDays: [null],
      );
      final facts = pdfHeaderFacts(
        model: model,
        anonymized: false,
        cycleIndex: 0,
      );

      expect(valueOf(facts, 'Name'), '—');
      expect(valueOf(facts, 'Geburtsdatum'), '24.12.1980');
      // The count-up can never be empty: it IS the cycle's ordinal (≥ 1).
      expect(valueOf(facts, 'Beobachtete Zyklen'), '1');
      // A first cycle has no completed earlier cycle and no earlier rise:
      // the "—" convention on both statistics.
      expect(valueOf(facts, 'Kürzester Zyklus'), '—');
      expect(valueOf(facts, 'Früheste erste höhere Messung'), '—');
    });

    test('the anonymize toggle hides name and birth date REGARDLESS of the '
        'stored settings and marks the document', () {
      final facts = pdfHeaderFacts(
        model: _fakeModel,
        anonymized: true,
        cycleIndex: 0,
      );

      expect(
        valueOf(facts, 'Name'),
        'anonymisiert',
        reason: 'the stored name must never reach the document',
      );
      expect(
        valueOf(facts, 'Geburtsdatum'),
        '—',
        reason: 'the birth date stays hidden, even when stored',
      );
      expect(
        facts.map((f) => f.value),
        isNot(contains('Maria Muster')),
        reason: 'no identifying value anywhere in the header facts',
      );
      expect(
        facts.any(
          (f) => f.label == 'Anonymisierung' && f.value == 'anonymisiert',
        ),
        isTrue,
        reason: 'the marker line states that the export was anonymized',
      );
    });

    test('the earliest header fact prints "—" when the record fact has no '
        'umrandete value', () {
      final model = PdfExportModel(
        cycles: const [],
        markOpenedIndexes: const [0],
        overlays: const [],
        observedCyclesOutsideApp: 0,
        name: null,
        birthDate: null,
        shortestCycleLengths: [28],
        earliestFirstHigherCycleDays: [null],
      );
      final facts = pdfHeaderFacts(
        model: model,
        anonymized: false,
        cycleIndex: 0,
      );
      expect(valueOf(facts, 'Früheste erste höhere Messung'), '—');
    });

    test('the earliest header fact prints the record\'s umrandete figure '
        'as is — the header never derives a figure of its own', () {
      final model = PdfExportModel(
        cycles: const [],
        markOpenedIndexes: const [0],
        overlays: const [],
        observedCyclesOutsideApp: 0,
        name: null,
        birthDate: null,
        shortestCycleLengths: [28],
        earliestFirstHigherCycleDays: [14],
      );
      final facts = pdfHeaderFacts(
        model: model,
        anonymized: false,
        cycleIndex: 0,
      );
      expect(valueOf(facts, 'Früheste erste höhere Messung'), 'Zyklustag 14');
    });

    test('the three cumulative facts are read PER CYCLE at the given '
        'cycleIndex (the paper-form count-up point of view)', () {
      final model = PdfExportModel(
        cycles: const [],
        markOpenedIndexes: const [0, 1],
        overlays: const [],
        observedCyclesOutsideApp: 0,
        name: null,
        birthDate: null,
        shortestCycleLengths: [27, 25],
        earliestFirstHigherCycleDays: [14, 12],
      );
      final first = pdfHeaderFacts(
        model: model,
        anonymized: false,
        cycleIndex: 0,
      );
      final second = pdfHeaderFacts(
        model: model,
        anonymized: false,
        cycleIndex: 1,
      );
      expect(valueOf(first, 'Beobachtete Zyklen'), '1');
      expect(valueOf(first, 'Kürzester Zyklus'), '27 Tage');
      expect(valueOf(first, 'Früheste erste höhere Messung'), 'Zyklustag 14');
      expect(valueOf(second, 'Beobachtete Zyklen'), '2');
      expect(valueOf(second, 'Kürzester Zyklus'), '25 Tage');
      expect(valueOf(second, 'Früheste erste höhere Messung'), 'Zyklustag 12');
    });

    test('"Beobachtete Zyklen" is the SAME source figure as the "Zyklus N" '
        'header line: model.ordinalOf(cycleIndex) — the count and the '
        'cycle number cannot drift', () {
      final facts = pdfHeaderFacts(
        model: _fakeModel,
        anonymized: false,
        cycleIndex: 0,
      );
      expect(
        valueOf(facts, 'Beobachtete Zyklen'),
        '${_fakeModel.ordinalOf(0)}',
      );
    });

    group('the observation window fact (Zykluszeitraum)', () {
      test('the window row carries the exported cycle\'s dates WITH year', () {
        final facts = pdfHeaderFacts(
          model: _fakeModel,
          anonymized: false,
          cycleIndex: 0,
          cycleWindow: (
            first: DateTime.utc(2026, 3, 1),
            last: DateTime.utc(2026, 3, 28),
          ),
        );
        expect(valueOf(facts, 'Zykluszeitraum'), '01.03.2026 – 28.03.2026');
      });

      test('anonymization hides name and birth date, NOT the observation '
          'window — the year stays on the anonymized export too', () {
        final facts = pdfHeaderFacts(
          model: _fakeModel,
          anonymized: true,
          cycleIndex: 0,
          cycleWindow: (
            first: DateTime.utc(2026, 3, 29),
            last: DateTime.utc(2026, 5, 2),
          ),
        );
        expect(valueOf(facts, 'Zykluszeitraum'), '29.03.2026 – 02.05.2026');
        expect(valueOf(facts, 'Name'), 'anonymisiert');
      });

      test('a page outside any cycle facts (degenerate) keeps the "—"', () {
        final facts = pdfHeaderFacts(
          model: _fakeModel,
          anonymized: false,
          cycleIndex: 0,
        );
        expect(
          facts.any((f) => f.label == 'Zykluszeitraum'),
          isFalse,
          reason: 'no window was carried — the fact row never renders',
        );
      });
    });
  });

  group('weekend shading (the cycle tab\'s weekend bands, print-friendly)', () {
    // The fixture's first cycle runs Mar 1–28 2026 — Mar 1 is a SUNDAY, so
    // the tracked weekend dates are 1, 7, 8, 14, 15, 21, 22, 28 and the
    // bands occupy window positions 0, 6, 7, 13, 14, 20, 21, 27.
    test('the window\'s weekend columns derive from the tracked dates', () {
      expect(weekendPositions(fixtureModel().cycles.first.cycle.days), [
        0, 6, 7, 13, 14, 20, 21, 27, //
      ]);
    });

    test('the generated page carries fills in the light-gray weekend '
        'shade — repeated: one band through EVERY scaffold row per '
        'weekend column', () async {
      final bytes = await generateFixture();
      final tuples = fillColorTuples(firstPageContentStream(bytes));
      final weekendFills = [
        for (final t in tuples)
          if (t.every((c) => (c - _weekendShade).abs() < 0.002)) t,
      ];
      expect(weekendFills, isNotEmpty);
      // Cycle 1's page: 8 weekend columns × the rows the band runs
      // through (day numbers … notes area) plus the painted plot bands —
      // well above 8 fill emissions.
      expect(weekendFills.length, greaterThanOrEqualTo(8));
    });
  });

  group('cycle-day numbering (calendar offsets from the cycle start)', () {
    test("'1. Tag' labels the start day; the numbers keep counting per "
        'calendar day on the normal, gapless fixture', () {
      final cycleOne = fixtureModel().cycles.first;
      final cycleStart = DateOnly.normalize(cycleOne.cycle.startDate);
      expect(
        [
          for (final day in cycleOne.cycle.days.take(3))
            cycleDayNumberLabel(DateOnly.daysBetween(day.date, cycleStart)),
        ],
        ['1. Tag', '2.', '3.'],
        reason: 'the tracked date at offset k labels cycle day k + 1',
      );
    });

    test('a cycleStart mark on an untracked gap day (start BEFORE the first '
        'tracked day): the first column still labels the calendar cycle '
        'day, and the columns behind an interior untracked gap show the '
        'correct offset', () {
      // The mark is placed Apr 1, but the first TRACKED day is Apr 2; the
      // tracked list then skips Apr 4–6 (an interior untracked gap). The
      // labels must follow the CALENDAR offsets from the mark — never the
      // tracked positions (which would print "1." with a lost day).
      final entries = [
        DailyEntry(date: d(4, 2), bbtC: 36.5),
        DailyEntry(date: d(4, 3), bbtC: 36.4),
        DailyEntry(date: d(4, 7), bbtC: 36.5),
        DailyEntry(date: d(4, 8), bbtC: 36.6),
      ];
      final marks = [CycleMark(date: d(4, 1), type: CycleMarkTypes.cycleStart)];
      final model = buildPdfExportModel(entries: entries, marks: marks);
      final cycle = model.cycles.single;
      final cycleStart = DateOnly.normalize(cycle.cycle.startDate);
      expect(
        cycleStart,
        d(4, 1),
        reason:
            'the opening mark anchors the cycle a day BEFORE the first '
            'tracked day — offsets from it must count that gap day',
      );
      // The first page window's leading columns, labeled exactly the way
      // the day-number row labels them (offset from the cycle start).
      expect(
        [
          for (final day in cycle.cycle.days.take(4))
            cycleDayNumberLabel(DateOnly.daysBetween(day.date, cycleStart)),
        ],
        ['2.', '3.', '7.', '8.'],
        reason:
            'the untracked Apr 4–6 own no column; the next tracked '
            'column (Apr 7) carries the calendar cycle day 7',
      );
    });
  });

  group('generated bytes (smoke)', () {
    test(
      'the byte stream is non-empty and starts with the PDF signature',
      () async {
        final bytes = await generateFixture();
        expect(bytes, isNotEmpty);
        final signature = '%PDF-'.codeUnits;
        for (var i = 0; i < signature.length; i++) {
          expect(bytes[i], signature[i]);
        }
      },
    );

    test('the document page count equals the layout planner split (1 cycle '
        'per page under the 40-column budget: 28-day -> 1 page, '
        '31-day -> 1 page)', () async {
      final bytes = await generateFixture();
      final plan = planCyclePages(
        fixtureModel().cycles
            .map((e) => cycleSpanDays(e.cycle).length)
            .toList(),
      );
      expect(plan.length, 2);
      expect(countPageMarkers(bytes), plan.length);
    });

    test('notes with umlauts and non-Latin-1 glyphs survive the generation '
        '(bundled TTF registered as base font)', () async {
      // The pure assertion: generation does not throw and produces a
      // signed document; the TTF is the registered base font, so text
      // beyond Latin-1 renders instead of silently misrendering (the
      // fixture note carries umlaut composition marks and Cyrillic/Greek
      // glyphs the CoreFonts could never draw).
      final bytes = await generateFixture();
      expect(bytes, isNotEmpty);
      expect(bytes[0], 0x25); // '%'
      expect(bytes[1], 0x50); // 'P'
    });
  });

  group(
    'in-plot chart marks (sex X / mucus letters / peak dot / M / day numbers)',
    () {
      // The settled geometry: the text glyph rows pitch between the 0.1 °C
      // grid lines, BELOW the plot's top border (offsets −0.05 X / −0.15
      // peak dot / −0.25 letters / −0.35 Mittelschmerz M from the scale
      // max), while the day numbers anchor from the BOTTOM at
      // min + 0.05 — all INSIDE the plot. The page's pinned row seams frame
      // the plot REGION: the bleeding row's caption above, the temperature
      // value row's below (the sheet's strip rows end at bleeding — the M
      // and the numbers are in-plot glyphs). Rail-bound page x: margin (28)
      // + rail (58) + the day fraction × pdfColumnWidth.
      const x0 = 28 + 58;
      const plotHeightPt = 185; // the PDF plot's painted height
      const defaultSpan = 2.0; // the default display range 36–38 °C
      // The letters center (max − 0.25) sits span − 0.30 above the numbers
      // center (min + 0.05); the two rows' ink baselines track that gap on
      // the plot's °C scale.
      const lettersToNumbersGapPt =
          (defaultSpan - 0.30) * plotHeightPt / defaultSpan;

      double runY(List<PdfTextRun> runs, String exact) => runs
          .firstWhere(
            (r) => r.text == exact,
            orElse: () => throw TestFailure('no "$exact" text run rendered'),
          )
          .y;
      PdfTextRun? runOf(List<PdfTextRun> runs, String exact, double fontSize) =>
          runs
              .where(
                (r) => r.text == exact && (r.fontSize - fontSize).abs() < 0.05,
              )
              .firstOrNull;

      /// The small accent-filled circles (the letters/X draw as ink text; the
      /// only small accent fill in the plot is the peak dot — candidate arrow
      /// sticks are excluded by the width gate).
      List<PdfInkPath> accentDots(List<PdfInkPath> paths) => [
        for (final p in paths)
          if ((p.color[0] - 0x35 / 255).abs() < 0.004 &&
              (p.color[1] - 0x56 / 255).abs() < 0.004 &&
              (p.color[2] - 0xA8 / 255).abs() < 0.004 &&
              (p.maxX - p.minX) >= 3 &&
              (p.maxX - p.minX) <= 6.5 &&
              (p.maxY - p.minY) >= 3 &&
              (p.maxY - p.minY) <= 6.5)
            p,
      ];

      /// The halo backings: paper-white fills behind the in-plot glyphs (the
      /// PDF's halo equivalent — see the backing's slot comment in
      /// cycle_pdf.dart).
      List<PdfInkPath> whiteBackings(List<PdfInkPath> paths) => [
        for (final p in paths)
          if (p.color.every((c) => (c - 1.0).abs() < 0.002)) p,
      ];

      /// Whether a white backing of [paths] sits in [column]'s day column,
      /// vertically centered on [inkBaselineY] — a text glyph's halo box
      /// shares the ink's slot center.
      bool backedIn(List<PdfInkPath> paths, int column, double inkBaselineY) {
        return whiteBackings(paths).any((p) {
          final cx = (p.minX + p.maxX) / 2;
          final cy = (p.minY + p.maxY) / 2;
          return cx > x0 + column * pdfColumnWidth + 1 &&
              cx < x0 + (column + 1) * pdfColumnWidth - 1 &&
              (cy - inkBaselineY).abs() < 3.5;
        });
      }

      /// Whether any backing of [paths] sits in [column]'s day column —
      /// column-only, for the rows whose ink (and backing) must be absent.
      bool backedInColumn(List<PdfInkPath> paths, int column) {
        return whiteBackings(paths).any(
          (p) =>
              (p.minX + p.maxX) / 2 > x0 + column * pdfColumnWidth + 1 &&
              (p.minX + p.maxX) / 2 < x0 + (column + 1) * pdfColumnWidth - 1,
        );
      }

      /// The evaluation day-number ink runs: the digits 1–6 at the
      /// low-number band's ink size (the numbers' family in the export).
      bool isNumberRun(PdfTextRun r) =>
          {'1', '2', '3', '4', '5', '6'}.contains(r.text) &&
          (r.fontSize - 5.2).abs() < 0.05;

      test(
        'the sex X marks render in the plot at their per-timing slots',
        () async {
          final bytes = await generateMarkFixture();
          final (runs, _) = extractPageContent(bytes);
          final blutungY = runY(runs, 'Blutung');
          final tempY = runY(runs, 'Temperatur');
          bool inPlot(PdfTextRun r) => r.y > tempY && r.y < blutungY;
          final xRuns = [
            for (final r in runs)
              if (r.text == 'X' && inPlot(r)) r,
          ]..sort((a, b) => a.x.compareTo(b.x));
          // Day 2 carries all three timings (slots 1/6, 1/2, 5/6), day 3 end
          // only (5/6). All X runs share one glyph, so their BASELINE-x offsets
          // fold to exactly the slot fractions of the column pitch.
          expect(xRuns.map((r) => r.x).toList(), [
            closeTo(x0 + (2 + 1 / 6) * pdfColumnWidth, 2.5),
            closeTo(x0 + (2 + 1 / 2) * pdfColumnWidth, 2.5),
            closeTo(x0 + (2 + 5 / 6) * pdfColumnWidth, 2.5),
            closeTo(x0 + (3 + 5 / 6) * pdfColumnWidth, 2.5),
          ], reason: 'the timing slots sit at 1/6, 1/2, 5/6 of the day column');
          expect(
            xRuns,
            hasLength(4),
            reason:
                'the paper-form sex strip row is gone — only the in-plot Xs remain',
          );
        },
      );

      test('the mucus sign letters ride their day columns in the plot (S with '
          'its quality superscript, f/S), pitched below the sex row', () async {
        final bytes = await generateMarkFixture();
        final (runs, _) = extractPageContent(bytes);
        final blutungY = runY(runs, 'Blutung');
        final tempY = runY(runs, 'Temperatur');
        bool inPlot(PdfTextRun r) => r.y > tempY && r.y < blutungY;
        final s = runOf(runs, 'S', 6.5);
        final fs = runOf(runs, 'f/S', 6.5);
        final quality = runOf(runs, 'EW', 4.8);
        expect(
          s,
          isNotNull,
          reason:
              'the S letter renders INSIDE the plot '
              '(the in-plot letters use the row letters\' _label size)',
        );
        expect(fs, isNotNull, reason: 'f/S renders in the plot too');
        expect(quality, isNotNull, reason: 'the quality token renders with S');
        for (final (name, run) in [('S', s!), ('f/S', fs!), ('EW', quality!)]) {
          expect(
            inPlot(run),
            isTrue,
            reason: 'the $name letter renders inside the plot region',
          );
        }
        // Both letter baselines share the mucus row; the quality superscript
        // rides raised (the rows' composed glyph, token raised by its offset).
        expect((s.y - fs.y).abs(), lessThan(0.8));
        expect(quality.y, greaterThan(s.y + 0.5));
        // The settled row pitches: the X row center at max − 0.05, the letters
        // at max − 0.25 → 0.2 K apart on the plot's °C scale.
        final sexY = runOf(runs, 'X', 6.5)!.y;
        expect(
          sexY - s.y,
          closeTo((0.25 - 0.05) * plotHeightPt / defaultSpan, 0.8),
        );
        // The letters center in their day columns (S on day 5, f/S on day 6;
        // the run boxes are width-constrained, so the baselines fall inside
        // the column interval).
        expect(
          s.x,
          allOf(
            greaterThan(x0 + 5 * pdfColumnWidth + 0.5),
            lessThan(x0 + 6 * pdfColumnWidth - 0.5),
          ),
        );
        expect(
          fs.x,
          allOf(
            greaterThan(x0 + 6 * pdfColumnWidth + 0.5),
            lessThan(x0 + 7 * pdfColumnWidth - 0.5),
          ),
        );
      });

      test(
        'the mucus peak dot renders as one small accent circle between the '
        'sex row and the letter row, centered in the peak day\'s column',
        () async {
          final bytes = await generateMarkFixture();
          final (runs, paths) = extractPageContent(bytes);
          final blutungY = runY(runs, 'Blutung');
          final s = runOf(runs, 'S', 6.5);
          final sexY = runOf(runs, 'X', 6.5)!.y;
          final dots = accentDots(paths);
          expect(
            dots,
            hasLength(1),
            reason: 'the peak-marked day carries exactly one peak dot',
          );
          final dot = dots.single;
          final centerX = (dot.minX + dot.maxX) / 2;
          final centerY = (dot.minY + dot.maxY) / 2;
          // The dot rides the peak day's column center (day 5), above the letter
          // row but below the sex row — the shared −0.15 K gap.
          expect(centerX, closeTo(x0 + 5.5 * pdfColumnWidth, 1.2));
          expect(
            centerY,
            lessThan(blutungY),
            reason: 'the dot renders inside the plot',
          );
          expect(centerY, greaterThan(s!.y + 2));
          expect(centerY, lessThan(sexY - 4));
        },
      );

      test('a peak mark on a DATA-LESS span-extension placeholder day paints '
          'its dot like any other day — the render reads the marks artifact, '
          'not the entries', () async {
        // Mar 1–14 carry entries; `today` pins the span extension to
        // Mar 17, so Mar 15–17 are entry-less placeholder columns and
        // the peak mark lands on placeholder column 14 (Mar 15).
        final model = buildPdfExportModel(
          entries: markFixtureEntries(),
          marks: [
            CycleMark(date: d(3, 1), type: CycleMarkTypes.cycleStart),
            CycleMark(date: d(3, 15), type: CycleMarkTypes.mucusPeakDay),
          ],
          temperatureRange: TemperatureRange.defaults,
          today: d(3, 17),
        );
        final bytes = await generatePdfBytes(
          model: model,
          fontBytes: fixtureFontBytes(),
          options: PdfExportOptions(anonymized: false),
          compress: false,
        );
        final (runs, paths) = extractPageContent(bytes);
        final blutungY = runY(runs, 'Blutung');
        final tempY = runY(runs, 'Temperatur');
        bool inPlot(PdfTextRun r) => r.y > tempY && r.y < blutungY;
        final dots = accentDots(paths);
        expect(
          dots,
          hasLength(1),
          reason: 'the placeholder-day peak mark carries exactly one dot',
        );
        expect(
          (dots.single.minX + dots.single.maxX) / 2,
          closeTo(x0 + 14.5 * pdfColumnWidth, 1.2),
          reason: 'the dot centers in the placeholder day column (Mar 15)',
        );
        final columnStart = x0 + 14 * pdfColumnWidth + 0.5;
        final columnEnd = x0 + 15 * pdfColumnWidth - 0.5;
        final joinedInk = [
          for (final r in runs)
            if (inPlot(r) &&
                r.x > columnStart &&
                r.x < columnEnd &&
                {4.8, 5.2, 6.5}.any((s) => (r.fontSize - s).abs() < 0.05))
              r,
        ];
        expect(
          joinedInk,
          isEmpty,
          reason: 'no mucus letter or day number joins the empty column',
        );
      });

      test('the Mittelschmerz letter M renders INSIDE the plot at the −0.35 '
          'pitch, below the mucus letters, centered in its record day\'s '
          'column', () async {
        final bytes = await generateMarkFixture();
        final (runs, _) = extractPageContent(bytes);
        final blutungY = runY(runs, 'Blutung');
        final tempY = runY(runs, 'Temperatur');
        bool inPlot(PdfTextRun r) => r.y > tempY && r.y < blutungY;
        final mRuns = [
          for (final r in runs)
            if (r.text == 'M' && inPlot(r)) r,
        ];
        expect(
          mRuns,
          hasLength(1),
          reason: 'the plot carries exactly one Mittelschmerz M',
        );
        final m = mRuns.single;
        expect(
          m.fontSize,
          closeTo(6.5, 0.05),
          reason: "the M shares the in-plot letters' ink family (_label)",
        );
        // The M pitch: 0.1 K below the letters row.
        final s = runOf(runs, 'S', 6.5)!;
        expect(
          s.y - m.y,
          closeTo((0.35 - 0.25) * plotHeightPt / defaultSpan, 0.8),
        );
        expect(
          m.x,
          allOf(
            greaterThan(x0 + 8 * pdfColumnWidth + 0.5),
            lessThan(x0 + 9 * pdfColumnWidth - 0.5),
          ),
          reason: "the M centers in the fixture day's column (day 8)",
        );
      });

      test(
        'the 1–6 evaluation numbers render INSIDE the plot near the '
        'bottom, one per low column, in the low-number band\'s ink family',
        () async {
          final bytes = await generateNumberFixture();
          final (runs, paths) = extractPageContent(bytes);
          final blutungY = runY(runs, 'Blutung');
          final tempY = runY(runs, 'Temperatur');
          bool inPlot(PdfTextRun r) => r.y > tempY && r.y < blutungY;
          final numberRuns = [
            for (final r in runs)
              if (isNumberRun(r)) r,
          ]..sort((a, b) => a.x.compareTo(b.x));
          expect(
            numberRuns.map((r) => r.text).toList(),
            ['6', '5', '4', '3', '2', '1'],
            reason:
                'the six low columns number from the first higher '
                'measurement backwards (the domain numbering, fed to the '
                'plot unchanged)',
          );
          expect(
            numberRuns.first.fontSize,
            closeTo(5.2, 0.05),
            reason: 'the numbers render in the low-number band\'s ink family',
          );
          for (final run in numberRuns) {
            expect(
              inPlot(run),
              isTrue,
              reason: "the number '${run.text}' renders inside the plot region",
            );
          }
          for (final (index, run) in numberRuns.indexed) {
            expect(
              run.x,
              allOf(
                greaterThan(x0 + index * pdfColumnWidth + 0.5),
                lessThan(x0 + (index + 1) * pdfColumnWidth - 0.5),
              ),
              reason:
                  "the number '${run.text}' centers in its low day's column",
            );
          }
          // The numbers ride the BOTTOM gridline gap: their ink baseline sits
          // `(span − 0.30) K` of plot scale below the letters row's baseline.
          final s = runOf(runs, 'S', 6.5)!;
          expect(s.y - numberRuns.first.y, closeTo(lettersToNumbersGapPt, 2.5));
          // On the in-plot seam each glyph renders on its halo backing.
          for (final (index, run) in numberRuns.indexed) {
            expect(
              backedIn(paths, index, run.y),
              isTrue,
              reason: "the number '${run.text}' rides its halo backing",
            );
          }
        },
      );

      test(
        'a paper-colored halo backing renders behind each in-plot glyph, '
        'shared with the ink\'s slot (the ink sits exactly over it)',
        () async {
          final bytes = await generateMarkFixture();
          final (runs, paths) = extractPageContent(bytes);
          final s = runOf(runs, 'S', 6.5)!;
          final m = [
            for (final r in runs)
              if (r.text == 'M') r,
          ].single;
          final dot = accentDots(paths).single;
          expect(
            backedIn(paths, 5, s.y),
            isTrue,
            reason: 'the mucus letters ride a backing in their column',
          );
          expect(
            backedIn(paths, 8, m.y),
            isTrue,
            reason: 'the M rides a backing in its column',
          );
          // The peak dot's halo circle: bigger than the dot and exactly
          // centered under it — dot diameter + 2 × the shared halo width.
          final circle = [
            for (final p in whiteBackings(paths))
              if (((p.minX + p.maxX) / 2 - (dot.minX + dot.maxX) / 2).abs() <
                      1.5 &&
                  ((p.minY + p.maxY) / 2 - (dot.minY + dot.maxY) / 2).abs() <
                      1.5)
                p,
          ];
          expect(
            circle,
            hasLength(1),
            reason: 'the dot rides exactly one backing',
          );
          expect(
            circle.single.maxX - circle.single.minX,
            allOf(greaterThan(dot.maxX - dot.minX), lessThan(11)),
            reason: 'the halo circle outgrows the ink dot without blotting out',
          );
        },
      );

      test('the paper form drops the mucus band, the sex row, the '
          'Mittelschmerz row and the Zahl row — bleeding is the last strip '
          'row above the glyphs inside the plot', () async {
        final bytes = await generateMarkFixture();
        final (runs, _) = extractPageContent(bytes);
        final rendered = runs.map((r) => r.text).toList();
        expect(
          rendered,
          isNot(contains('Zeichen')),
          reason: 'the mucus band renders as in-plot glyphs, not a strip row',
        );
        expect(
          rendered,
          isNot(contains('Sex')),
          reason: 'the Xs render in the plot, not as a strip row',
        );
        expect(
          rendered,
          isNot(contains('Mittelschmerz')),
          reason: 'the M renders in the plot, not as a strip row',
        );
        expect(
          rendered,
          isNot(contains('Zahl')),
          reason: 'the day numbers render in the plot, not as a strip row',
        );
        const kept = [
          // The calendar day-number row: the cycle-day labels above the
          // plot, distinct from the evaluation numbering inside it.
          'Zyklustag',
          'Datum',
          'Blutung',
          // The exporter draws words as separate runs; the caption's anchor
          // word is 'Temperatur'.
          'Temperatur',
          'Zeit',
          'Störung',
          // The merged band's one rail caption — the cervix and pain zones
          // share it.
          'Notizen',
        ];
        for (final caption in kept) {
          expect(
            rendered,
            contains(caption),
            reason: 'the kept scaffold row "$caption" stays',
          );
        }
        for (final dropped in ['Muttermund', 'Schmerz']) {
          expect(
            rendered,
            isNot(contains(dropped)),
            reason:
                'the merged band\'s row carries no "$dropped" caption — '
                'the zones ride its one row',
          );
        }
      });

      test(
        'a span-0.20 range keeps the sex row AND the peak dot (decoupled '
        'rows); the mucus letters, the M and their halo backs hide',
        () async {
          final bytes = await generateMarkFixture(
            range: const TemperatureRange(min: 37.8, max: 38.0),
          );
          final (runs, paths) = extractPageContent(bytes);
          final blutungY = runY(runs, 'Blutung');
          final tempY = runY(runs, 'Temperatur');
          bool inPlot(PdfTextRun r) => r.y > tempY && r.y < blutungY;
          // The letters render nowhere on the page when hidden.
          expect(
            runs.where(
              (r) => r.text == 'S' || r.text == 'f/S' || r.text == 'EW',
            ),
            isEmpty,
          );
          expect(
            runs.where((r) => r.text == 'M'),
            isEmpty,
            reason: 'the M hides with its own row below the letters',
          );
          final xRuns = [
            for (final r in runs)
              if (r.text == 'X' && inPlot(r)) r,
          ];
          expect(
            xRuns,
            hasLength(4),
            reason: 'the sex Xs stay, at their timing slots in the plot',
          );
          expect(
            accentDots(paths),
            hasLength(1),
            reason:
                'the peak dot keeps ITS OWN row (0.15): at span 0.20 it '
                'stays visible, decoupled from the letters band',
          );
          final dot = accentDots(paths).single;
          // A hidden row's halo backs follow their glyph's visibility.
          expect(
            backedInColumn(paths, 6),
            isFalse,
            reason: "the hidden f/S letter's backing hides too",
          );
          expect(
            backedInColumn(paths, 8),
            isFalse,
            reason: "the hidden M's backing hides too",
          );
          final circle = [
            for (final p in whiteBackings(paths))
              if (((p.minX + p.maxX) / 2 - (dot.minX + dot.maxX) / 2).abs() <
                      1.5 &&
                  ((p.minY + p.maxY) / 2 - (dot.minY + dot.maxY) / 2).abs() <
                      1.5)
                p,
          ];
          expect(
            circle,
            hasLength(1),
            reason: 'the visible dot keeps its backing',
          );
        },
      );

      test('a span below 0.10 hides the bottom-anchored day numbers with '
          'their row — no number ink and no halo backing anywhere', () async {
        final bytes = await generateNumberFixture(
          range: const TemperatureRange(min: 37.9, max: 37.96),
        );
        final (runs, paths) = extractPageContent(bytes);
        expect(
          runs.where(isNumberRun),
          isEmpty,
          reason:
              'the numbers hide when their center exceeds the top edge '
              'margin: min + 0.05 ≤ max − 0.05 fails at span 0.06',
        );
        expect(
          whiteBackings(paths),
          isEmpty,
          reason: 'the halo backs follow their glyph\'s row visibility',
        );
        expect(
          accentDots(paths),
          isEmpty,
          reason: 'the other in-plot rows hide at this span too',
        );
      });
    },
  );

  group('merged notes band (cervix zones, pain and notes in one row)', () {
    const x0 = 28 + 58;

    double runYOf(List<PdfTextRun> runs, String exact) => runs
        .firstWhere(
          (r) => r.text == exact,
          orElse: () => throw TestFailure('no "$exact" text run rendered'),
        )
        .y;

    /// The painted cervix openings: the filled ink-dark circles (the
    /// closed dot fills; the outlined rings stroke and don't fill), ONE
    /// per cervix day, in the merged band's region (below the disturbance
    /// row's caption — the temperature dots live above it).
    List<PdfInkPath> bandDots(List<PdfInkPath> paths, double bandTopY) => [
      for (final p in paths)
        if (p.color.every((c) => c <= 0.2) &&
            (p.maxX - p.minX) >= 3.4 &&
            (p.maxX - p.minX) <= 4.6 &&
            ((p.maxX - p.minX) - (p.maxY - p.minY)).abs() <= 1 &&
            p.maxY < bandTopY)
          p,
    ];

    /// The painted cervix rings: the stroked ink circles (see [bandDots]
    /// for the closed dot's fill counterpart), gated into the merged
    /// band's region the same way.
    List<PdfInkPath> bandRings(List<PdfInkPath> paths, double bandTopY) => [
      for (final p in paths)
        if (p.color.every((c) => c <= 0.2) &&
            (p.maxX - p.minX) >= 5 &&
            (p.maxX - p.minX) <= 9 &&
            ((p.maxX - p.minX) - (p.maxY - p.minY)).abs() <= 1 &&
            p.maxY < bandTopY)
          p,
    ];

    test('the band columns carry the cervix letters and the pain B at the '
        'tiny ink size, like the cycle tab\'s glyph rows', () async {
      final bytes = await generateBandFixture();
      final (runs, _) = extractPageContent(bytes);
      List<PdfTextRun> byText(String text, double size) => runs
          .where((r) => r.text == text && (r.fontSize - size).abs() < 0.05)
          .toList();
      expect(
        byText('w', 5.2),
        isNotEmpty,
        reason: "day 0's soft firmness 'w' renders its letter",
      );
      expect(
        byText('h-w', 5.2),
        isNotEmpty,
        reason: "day 1's halfSoft firmness 'h-w' renders its letter",
      );
      expect(
        byText('B', 5.2),
        isNotEmpty,
        reason: "the breast-pain days' B renders in the band's pain zone",
      );
    });

    test('the middle and open openings paint their outlined rings in their '
        'day columns inside the band, sized 6 / 8 pt like the screen '
        'shapes', () async {
      final bytes = await generateBandFixture();
      final (runs, paths) = extractPageContent(bytes);
      final stoerungY = runYOf(runs, 'Störung');
      final rings = bandRings(paths, stoerungY);
      List<PdfInkPath> ringsIn(int column) => [
        for (final p in rings)
          if ((p.minX + p.maxX) / 2 > x0 + column * pdfColumnWidth + 1 &&
              (p.minX + p.maxX) / 2 < x0 + (column + 1) * pdfColumnWidth - 1)
            p,
      ];
      expect(
        ringsIn(2),
        isEmpty,
        reason: "day 2 records no cervix opening — the band paints no rings",
      );
      final middleRing = ringsIn(3).single;
      expect(
        middleRing.maxX - middleRing.minX,
        closeTo(cervixMiddleCircleSize, 0.05),
        reason: "day 3's middle opening paints the 6 pt circle's width",
      );
      expect(
        middleRing.maxY - middleRing.minY,
        closeTo(cervixMiddleCircleSize, 0.05),
        reason: "day 3's middle ring paints square",
      );
      final openRing = ringsIn(1).single;
      expect(
        openRing.maxX - openRing.minX,
        closeTo(cervixOpenCircleSize, 0.05),
        reason: "day 1's open opening paints the 8 pt circle's width",
      );
      expect(
        openRing.maxY - openRing.minY,
        closeTo(cervixOpenCircleSize, 0.05),
        reason: "day 1's open ring paints square",
      );
    });

    test('the closed opening paints its dot in its day column inside the '
        'band; the cervix-free day paints none', () async {
      final bytes = await generateBandFixture();
      final (runs, paths) = extractPageContent(bytes);
      final stoerungY = runYOf(runs, 'Störung');
      final dots = bandDots(paths, stoerungY);
      final day0Dots = [
        for (final p in dots)
          if ((p.minX + p.maxX) / 2 > x0 + 0 * pdfColumnWidth + 1 &&
              (p.minX + p.maxX) / 2 < x0 + 1 * pdfColumnWidth - 1)
            p,
      ];
      expect(
        day0Dots,
        hasLength(1),
        reason: "day 0's closed opening paints exactly one filled 4 pt dot",
      );
      final day2Dots = [
        for (final p in dots)
          if ((p.minX + p.maxX) / 2 > x0 + 2 * pdfColumnWidth + 1 &&
              (p.minX + p.maxX) / 2 < x0 + 3 * pdfColumnWidth - 1)
            p,
      ];
      expect(
        day2Dots,
        isEmpty,
        reason: "day 2 records no cervix — the band paints no circles",
      );
    });

    test(
      'the note text anchors at its zone top, like the cycle tab\'s '
      'reading direction (the vertical line reads starting at the top)',
      () async {
        final bytes = await generateBandFixture();
        final (runs, _) = extractPageContent(bytes);
        // The caption sits at the band's top edge; a top-anchored note's
        // first glyph lands a note zone's worth below it — the cervix-free
        // pain day's noteTop is 12 pt (pain row only). The TJ runs split
        // words, so the lookup anchors on the notes' FIRST fragments (the
        // fragment of the line's start).
        final captionY = runYOf(runs, 'Notizen');
        final day2NoteY = runs
            .firstWhere(
              (r) =>
                  r.text.contains('Zweite') && (r.fontSize - 5.2).abs() < 0.05,
              orElse: () => throw TestFailure(
                "no day-2 note text run ('Zweite' fragment) rendered",
              ),
            )
            .y;
        expect(
          captionY - day2NoteY,
          lessThan(20),
          reason:
              'the note starts at the top of its zone, a pain row below '
              "the band's caption — not mid-band as a centered/bottom-up "
              'line would place it',
        );
        // The cervix-stack day's note sits below the full 52 pt top block.
        final day0NoteY = runs
            .firstWhere(
              (r) =>
                  r.text.contains('Erste') && (r.fontSize - 5.2).abs() < 0.05,
              orElse: () => throw TestFailure(
                "no day-0 note text run ('Erste' fragment) rendered",
              ),
            )
            .y;
        expect(
          captionY - day0NoteY,
          inInclusiveRange(40, 65),
          reason:
              "day 0's note starts below the 30 pt glyph zone, 10 pt letter "
              'row and 12 pt pain row (~52 pt)',
        );
      },
    );
    test('the merged band\'s rotated cells read top→bottom (the cycle '
        "tab's direction): pdfRotatedTextAngle is −π/2, pw's top→down "
        'quarter turn', () {
      expect(pdfRotatedTextAngle, closeTo(-math.pi / 2, 1e-9));
    });
  });
}
