// Tests of the PDF generation layer (lib/pdf/cycle_pdf.dart): the pure
// header-facts function (with the anonymize mapping) and the byte-stream
// smoke checks of the generated document.
//
// Structural page-count checks rely on the layout planner (the one-cycle-
// per-page rule); the generated byte stream itself is only smoke-checked
// (non-empty, PDF signature, the uncompressed page markers) — the PDF
// structure is deliberately not parsed beyond countable markers.
import 'dart:io';

import 'package:cycle_app/domain/marks.dart';
import 'package:cycle_app/domain/models.dart';
import 'package:cycle_app/domain/pdf_export_model.dart';
import 'package:cycle_app/pdf/cycle_pdf.dart';
import 'package:cycle_app/pdf/pdf_layout.dart';
import 'package:flutter_test/flutter_test.dart';

DateTime d(int month, int day) => DateTime.utc(2026, month, day);

const _fakeModel = PdfExportModel(
  cycles: [],
  overlays: [],
  observedCyclesOutsideApp: 3,
  name: 'Maria Muster',
  birthDate: null,
  shortestCycleLength: 27,
  earliestFirstHigherCycleDay: (any: 14, afterMucusPeak: 14),
);

/// Fixture data: two mark-opened cycles (Mar 1..28: 28 days; Mar 29..Apr 28:
/// 31 days), notes on some days with umlauts and non-Latin-1 glyphs.
List<DailyEntry> fixtureEntries() => [
  for (var i = 0; i < 28; i++)
    DailyEntry(
      date: d(3, 1 + i),
      bbtC: 36.0 + (i % 10) / 10,
      notes: i == 3
          ? 'Querdenken im Büro — schöner Tag ß'
          : (i == 10 ? 'Ж α ž' : null),
    ),
  for (var i = 0; i < 31; i++) DailyEntry(date: d(3, 29 + i), bbtC: 36.2),
];

List<CycleMark> fixtureMarks() => [
  CycleMark(date: d(3, 1), type: CycleMarkTypes.cycleStart),
  CycleMark(date: d(3, 29), type: CycleMarkTypes.cycleStart),
];

PdfExportModel fixtureModel() => buildPdfExportModel(
  entries: fixtureEntries(),
  marks: fixtureMarks(),
  observedCyclesOutsideApp: 3,
  name: 'Maria Muster',
  birthDate: d(12, 24),
  // The span extension runs the LAST cycle out to "today"; the fixture
  // pins the clock at the second cycle's last tracked day so the 2-cycle
  // plan below stays deterministic.
  today: d(4, 28),
);

/// The bundled asset font, read from the checkout (the smoke path mirrors
/// what the app loads via rootBundle; see lib/pdf/cycle_pdf.dart).
List<int> fixtureFontBytes() =>
    File('assets/fonts/NotoSans-Regular.ttf').readAsBytesSync();

/// Counts the uncompressed page markers: with `compress: false` every page
/// object dictionary appears verbatim as `/Type/Page/` (the `/Pages` node
/// does not match — its "Page" is followed by an "s", not a "/").
int countPageMarkers(List<int> bytes) {
  final pattern = '/Type/Page/'.codeUnits;
  var count = 0;
  for (var i = 0; i + pattern.length <= bytes.length; i++) {
    var hit = true;
    for (var j = 0; j < pattern.length; j++) {
      if (bytes[i + j] != pattern[j]) {
        hit = false;
        break;
      }
    }
    if (hit) count++;
  }
  return count;
}

String valueOf(List<({String label, String value})> facts, String label) =>
    facts.firstWhere((f) => f.label == label).value;

void main() {
  group('header facts (pure)', () {
    test('a named export shows the identifying values and the numbers', () {
      final facts = pdfHeaderFacts(model: _fakeModel, anonymized: false);

      expect(valueOf(facts, 'Name'), 'Maria Muster');
      // No birth date stored: the "—" convention.
      expect(valueOf(facts, 'Geburtsdatum'), '—');
      expect(valueOf(facts, 'Beobachtete Zyklen'), '3');
      expect(valueOf(facts, 'Kürzester Zyklus'), '27 Tage');
      expect(valueOf(facts, 'Früheste erste höhere Messung'), 'Zyklustag 14');
    });

    test('a stored birth date is formatted as the German calendar date', () {
      final model = PdfExportModel(
        cycles: const [],
        overlays: const [],
        observedCyclesOutsideApp: 0,
        name: null,
        birthDate: DateTime.utc(1980, 12, 24),
        shortestCycleLength: null,
        earliestFirstHigherCycleDay: (any: null, afterMucusPeak: null),
      );
      final facts = pdfHeaderFacts(model: model, anonymized: false);

      expect(valueOf(facts, 'Name'), '—');
      expect(valueOf(facts, 'Geburtsdatum'), '24.12.1980');
      expect(valueOf(facts, 'Beobachtete Zyklen'), '0');
      expect(valueOf(facts, 'Kürzester Zyklus'), '—');
      expect(valueOf(facts, 'Früheste erste höhere Messung'), '—');
    });

    test('the anonymize toggle hides name and birth date REGARDLESS of the '
        'stored settings and marks the document', () {
      final facts = pdfHeaderFacts(model: _fakeModel, anonymized: true);

      expect(
        valueOf(facts, 'Name'),
        'anonymisiert',
        reason: 'the stored name must never reach the document',
      );
      expect(
        valueOf(facts, 'Geburtsdatum'),
        '—',
        reason: 'the birth date stays hidden, even when stored',
      );
      expect(
        facts.map((f) => f.value),
        isNot(contains('Maria Muster')),
        reason: 'no identifying value anywhere in the header facts',
      );
      expect(
        facts.any(
          (f) => f.label == 'Anonymisierung' && f.value == 'anonymisiert',
        ),
        isTrue,
        reason: 'the marker line states that the export was anonymized',
      );
    });

    test('the earliest first higher prefers the "real" (after mucus peak) '
        'variant and falls back to any', () {
      final model = PdfExportModel(
        cycles: const [],
        overlays: const [],
        observedCyclesOutsideApp: 0,
        name: null,
        birthDate: null,
        shortestCycleLength: 28,
        earliestFirstHigherCycleDay: (any: 1, afterMucusPeak: 14),
      );
      final facts = pdfHeaderFacts(model: model, anonymized: false);
      expect(valueOf(facts, 'Früheste erste höhere Messung'), 'Zyklustag 14');
    });

    group('the observation window fact (Zykluszeitraum)', () {
      test('the window row carries the exported cycle\'s dates WITH year', () {
        final facts = pdfHeaderFacts(
          model: _fakeModel,
          anonymized: false,
          cycleWindow: (
            first: DateTime.utc(2026, 3, 1),
            last: DateTime.utc(2026, 3, 28),
          ),
        );
        expect(valueOf(facts, 'Zykluszeitraum'), '01.03.2026 – 28.03.2026');
      });

      test('anonymization hides name and birth date, NOT the observation '
          'window — the year stays on the anonymized export too', () {
        final facts = pdfHeaderFacts(
          model: _fakeModel,
          anonymized: true,
          cycleWindow: (
            first: DateTime.utc(2026, 3, 29),
            last: DateTime.utc(2026, 5, 2),
          ),
        );
        expect(valueOf(facts, 'Zykluszeitraum'), '29.03.2026 – 02.05.2026');
        expect(valueOf(facts, 'Name'), 'anonymisiert');
      });

      test('a page outside any cycle facts (degenerate) keeps the "—"', () {
        final facts = pdfHeaderFacts(model: _fakeModel, anonymized: false);
        expect(
          facts.any((f) => f.label == 'Zykluszeitraum'),
          isFalse,
          reason: 'no window was carried — the fact row never renders',
        );
      });
    });
  });

  group('generated bytes (smoke)', () {
    Future<List<int>> generate({bool anonymized = false}) => generatePdfBytes(
      model: fixtureModel(),
      fontBytes: fixtureFontBytes(),
      options: PdfExportOptions(anonymized: anonymized),
      compress: false,
    );

    test(
      'the byte stream is non-empty and starts with the PDF signature',
      () async {
        final bytes = await generate();
        expect(bytes, isNotEmpty);
        final signature = '%PDF-'.codeUnits;
        for (var i = 0; i < signature.length; i++) {
          expect(bytes[i], signature[i]);
        }
      },
    );

    test('the document page count equals the layout planner split (1 cycle '
        'per page under the 40-column budget: 28-day -> 1 page, '
        '31-day -> 1 page)', () async {
      final bytes = await generate();
      final plan = planCyclePages(
        fixtureModel().cycles.map((e) => e.cycle.days.length).toList(),
      );
      expect(plan.length, 2);
      expect(countPageMarkers(bytes), plan.length);
    });

    test('notes with umlauts and non-Latin-1 glyphs survive the generation '
        '(bundled TTF registered as base font)', () async {
      // The pure assertion: generation does not throw and produces a
      // signed document; the TTF is the registered base font, so text
      // beyond Latin-1 renders instead of silently misrendering (the
      // fixture note carries umlaut composition marks and Cyrillic/Greek
      // glyphs the CoreFonts could never draw).
      final bytes = await generate();
      expect(bytes, isNotEmpty);
      expect(bytes[0], 0x25); // '%'
      expect(bytes[1], 0x50); // 'P'
    });
  });
}
